server:
  port: 8080
  servlet:
    context-path: /
spring:
  redis:
    database: 10
    host: 127.0.0.1
    port: 6379
    password: ''
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
    timeout: 10000