server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/acp_user_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    database: 10
    host: 127.0.0.1
    port: 6379
    password: ''
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
    timeout: 10000
swagger:
  enabled: true
logging:
  level:
    dict.mapper: debug
  config: classpath:logback-spring.xml
mybatis-plus:
  type-aliases-package: dict.entity
  mapper-locations: classpath*:com/sunnyws/dict/mapper/**/*.xml